route:
  receiver: 'slack-notifications'
  
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#qrgenx-alerts'
    api_url: 'https://hooks.slack.com/services/T08NZB2834Y/B08NEPXLLH2/REDACTED'
    send_resolved: true
    title: '{{ .Status | title }}: {{ .CommonLabels.alertname }}'
    text: |-
      *Description*: {{ .CommonAnnotations.description }}
      *Details*: {{ .CommonAnnotations.summary }}
      *Graph*: <http://localhost:3000/d/qrgenx-main|View Dashboard>
